### ISSUE TITLE
remove_partial_seqs script

### ISSUE THREAD

**Issue by germelcar** [sortmerna/sortmerna#132]
Hello there:

I'm trying to rebuild the databases, but I can not find the "remove_partial_seqs.py" script. Also, I do not know what is the content of the "/home/evko1434/.bashrc" file from the line 24 of "hmmer_clean.sh" script.

Could you please share the script and the content of the .bashrc files?

Thanks in advance.

**Comment by jmeppley** [comment]
Has anyone located this script or successfully updated the sortmerna databases?

**Comment by ekopylova** [comment]
Databases are almost ready. Only QC and clustering by different % IDs remains.

⁣

**Comment by cmith44** [comment]
Closing this issue as databases have been updated: https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz
