### ISSUE TITLE
Taxonomy data for the included rfam databases

### ISSUE THREAD

**Issue by jrodnz** [sortmerna/sortmerna#158]
First off, thank you for a great tool for rRNA filtering of RNA-seq (the most popular in my group!).  

I am trying to double up on the usefulness of my sortmerna run by getting a rough estimate of sample contamination in my plant libraries using the OTU map (e.g. cross contamination with other plant DNA, fungal symbionts/pathogens etc.). 

However, unlike for the included silva databases, I could not find any resources on taxonomy of the 5s and 5.8s rfam databases included in the sortmerna package. Yesterday, I tried to see if I could figure this out myself by downloading all sequences from the RFAM 5s and 5.8s rRNA families ([RF00001](http://rfam.xfam.org/family/RF00001#tabview=tab1) and [RF00002](http://rfam.xfam.org/family/RF00002#tabview=tab1), respectively), but the overlap of sequence IDs is very small (Table 1). I figure that this is because I downloaded fewer sequences that you did according to the v2.1 LaTex manual (Table 2).

I would be grateful for any resources or information on how the sortmerna rfam 5s and 5.8s databases were built so I can extract some taxonomic information to go along with them. Thanks in advance!

___

**Table 1. Comparison of sequence ID's in sortmerna rfam databases to recent RFAM download**

Database | No. of 5s rRNA IDs | No. of 5.8s rRNA IDs
--- | --- | ---
sortmerna rfam db (after clustering) | 59513 | 13034
RFAM download | 109490 | 4070
overlap | 1250 | 73

**Table 2. Comparision of number of sequences in RFAM downloads**

rRNA family | sortmerna | RFAM (20180314)
--- | --- | ---
5s: RF00001 (?) | 116760  | 109490
5.8s: RF00002 (?) | 225185 | 4070

**Comment by ekopylova** [comment]
Hello @jrodnz,

Apologies for the delay in reply, I'll get to this early next week. Thanks for posting this question, it is likely relevant to many other users!

Jenya

**Comment by ufyksb** [comment]
Hello,
sortmerna is working great for me, but I have the same problem.
Where can I find any resource to translate rfam database id to taxonomy id?

**Comment by sghignone** [comment]
dear developer,
I have the same request: is it possible to have the  map for the taxonomy of the 5s and 5.8s rfam ?
Thanks a lot in advance

**Comment by cmith44** [comment]
@jrodnz @ufyksb @sghignone Closing this issue. Please refer to #329 for any discussion on database documentation, or #383 for discussion on taxonomy maps.
