### ISSUE TITLE
Job was killed during alignment

### ISSUE THREAD

**Issue by CBT127** [sortmerna/sortmerna#356]
Thank you very much for making the tool and maintaining it all the time. It has helped me a lot. Recently I ran into a problem while using it and I couldn't find a solution. The process was killed while running to alignment.The task error code is as follows,
`[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --index
Found value: 0 of previous flag: --index
Found flag: --threads
Found value: 4 of previous flag: --threads
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta of previous flag: --ref
Found flag: --workdir
Found value: /xtdisk/sortrna2 of previous flag: --workdir
Found flag: --reads
Found value: /xtdisk/trimmo/ERR2455136_1P.fastq.gz of previous flag: --reads
Found flag: --reads
Found value: /xtdisk/trimmo/ERR2455136_2P.fastq.gz of previous flag: --reads
Found flag: --aligned
Found value: ERR2455136_rRNA of previous flag: --aligned
Found flag: --other
Found value: ERR2455136_clean of previous flag: --other
Found flag: --paired_in
Previous flag: --paired_in is Boolean. Setting to True
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --out2
[opt_workdir:995] Using WORKDIR: "/xtdisk/sortrna2" as specified
[process:1483] Processing option: aligned with value: ERR2455136_rRNA
[process:1483] Processing option: fastx with value:
[process:1483] Processing option: index with value: 0
[opt_index:1182] using 'index' with specified value 0
[process:1483] Processing option: other with value: ERR2455136_clean
[process:1483] Processing option: out2 with value:
[process:1483] Processing option: paired_in with value:
[process:1483] Processing option: reads with value: /xtdisk/trimmo/ERR2455136_1P.fastq.gz
[opt_reads:98] Processing reads file [1] out of total [2] files
[process:1483] Processing option: reads with value: /xtdisk/trimmo/ERR2455136_2P.fastq.gz
[opt_reads:98] Processing reads file [2] out of total [2] files
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta
[opt_ref:158] Processing reference [1] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta
[opt_ref:158] Processing reference [2] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta
[opt_ref:158] Processing reference [3] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fasta
[opt_ref:158] Processing reference [4] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta
[opt_ref:158] Processing reference [5] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta
[opt_ref:158] Processing reference [6] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta
[opt_ref:158] Processing reference [7] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta" exists and is readable
[process:1483] Processing option: ref with value: /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta
[opt_ref:158] Processing reference [8] out of total [8] references
[opt_ref:206] File "/xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta" exists and is readable
[process:1483] Processing option: threads with value: 4
[process:1503] === Options processing done ===
[process:1504] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1248] Key-value DB location "/xtdisk/sortrna2/kvdb"
[validate_kvdbdir:1284] Creating KVDB directory: "/xtdisk/sortrna2/kvdb"
[validate_idxdir:1214] Using index directory: "/xtdisk/sortrna2/idx"
[validate_idxdir:1230] IDX directory: "/xtdisk/sortrna2/idx" exists and is not empty
[validate_readb_dir:1306] Using split reads directory : "/xtdisk/sortrna2/readb"
[validate_readb_dir:1322] split reads directory : "/xtdisk/sortrna2/readb" exists and is not empty
[main:62] Running command:
sortmerna --index 0 --threads 4 --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-b-23s-id98.fasta --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fast--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta --ref /xtdisk/oym_group/zhangxr/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta --ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta --workdir /xtdisk/baoygroup/zhangxr/sortrna2 --reads /xtdisk/trimmo/ERR2455136_1P.fastq.gz --reads /xtdisk/trimmo/ERR2455136_2P.fastq.gz --aligned ERR2455136_rRNA --other ERR24536_clean --paired_in --fastx --out2
[Index:102] Found 32 non-empty index files. Skipping indexing.
[init:108] Readfeed init started
[define_format:881] file: "/xtdisk/trimmo/ERR2455136_1P.fastq.gz" is FASTQ gzipped
[define_format:881] file: "/xtdisk/trimmo/ERR2455136_2P.fastq.gz" is FASTQ gzipped
[count_reads:915] started count  ...
[next:322] EOF FWD reached. Total reads: 24736634
[next:322] EOF REV reached. Total reads: 24736634
[count_reads:945] done count. Elapsed time: 292.745 sec. Total reads: 49473268
[init_split_files:967] added file: /xtdisk/sortrna2/readb/fwd_0.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/rev_0.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/fwd_1.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/rev_1.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/fwd_2.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/rev_2.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/fwd_3.fq.gz
[init_split_files:967] added file: /xtdisk/sortrna2/readb/rev_3.fq.gz
[is_split_ready:726] found existing readfeed descriptor /xtdisk/sortrna2/readb/readfeed
[split:605] start splitting. Using number of splits equals number of processing threads: 4
[clean:1098] found descriptor /xtdisk/sortrna2/readb/readfeed
[clean:1142] removing split file: /xtdisk/sortrna2/readb/fwd_0.fq.gz
[clean:1142] removing split file: /xtdisk/sortrna2/readb/rev_0.fq.gz
[clean:1142] removing split file: /xtdisk/sortrna2/readb/fwd_1.fq.gz
[clean:1142] removing split file: /xtdisk/sortrna2/readb/rev_1.fq.gz
[next:322] EOF FWD reached. Total reads: 24736634
[next:322] EOF REV reached. Total reads: 24736634
[split:717] Done splitting. Reads count: 49473268 Runtime sec: 3052.14

[init:135] Readfeed init done in sec [3344.91]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 49473268 all_reads_len= 6718686058 min_read_len= 36 max_read_len= 151 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matcheder_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 64
[align:163] Using number of Processor threads: 4
[Refstats:60] Index Statistics calculation starts ... done in: 5.38274 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 15 ...
[align:190] done in [2.05923] sec Memory KB: 503
[align:193] Loading references ...
[align:197] done in [0.130839] sec. Memory KB: 524
[align2:70] Processor 0 thread 140486643779328 started
[align2:70] Processor 1 thread 140486652172032 started
[align2:70] Processor 2 thread 140486660564736 started
[align2:70] Processor 3 thread 140486828353280 started
[next:455] EOF FWD reached. Total reads: 6184158
[next:455] EOF REV reached. Total reads: 6184158
[align2:133] Processor 3 thread 140486828353280 done. Processed 12368316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 2431566 Runtime sec: 8964.98
[next:455] EOF FWD reached. Total reads: 6184159
[next:455] EOF REV reached. Total reads: 6184159
[align2:133] Processor 1 thread 140486652172032 done. Processed 12368318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 2432132 Runtime sec: 9016.73
[next:455] EOF FWD reached. Total reads: 6184159
[next:455] EOF REV reached. Total reads: 6184159
[align2:133] Processor 0 thread 140486643779328 done. Processed 12368318 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 2431421 Runtime sec: 9040.12
[next:455] EOF FWD reached. Total reads: 6184158
[next:455] EOF REV reached. Total reads: 6184158
[align2:133] Processor 2 thread 140486660564736 done. Processed 12368316 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 2434480 Runtime sec: 9176.62
[align:220] done index: 0 part: 1 in 9176.62 sec Memory KB: 11238
[align:227] Index and References unloaded in 0.401312 sec. Memory KB: 11238
[align:185] Loading index: 1 part: 1/1 Memory KB: 11238 ...
[align:190] done in [2.25138] sec Memory KB: 11231
[align:193] Loading references ...
[align:197] done in [0.0257034] sec. Memory KB: 11231
[align2:70] Processor 1 thread 140486660564736 started
[align2:70] Processor 0 thread 140486828353280 started
[align2:70] Processor 2 thread 140486652172032 started
[align2:70] Processor 3 thread 140486643779328 started
Killed`
Could you help me figure out how to solve this problem?Sincerely thank you again!

**Comment by CBT127** [comment]
The version is 4.3.6 and input instruction is as follows:
`sortmerna --index 0 --threads 4  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta  \
--ref /xtdisk//tool/rtmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-nux/rRNA_databases/silva-arc-23s-id98.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databes/silva-euk-28s-id98.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta  \
--ref /xtdisk/tool/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8database-id98.fasta  \
--workdir /xtdisk/sortrna2  \
--reads /xtdisk/trimmo/ERR2455136_1P.fastq.gz --reads /xtdisk/trimmo/ERR2455136_2P.fastqz  \
--aligned "ERR2455136_rRNA" --other "ERR2455136_clean" --paired_in --fastx --out2
`

**Comment by biocodz** [comment]
Looks like a resource allocation problem. Please, have a look at the recent issue [355](https://github.com/biocore/sortmerna/issues/355)

**Comment by CBT127** [comment]
Thanks for your reply.I will try to run it on a different node and update the results later.

**Comment by CBT127** [comment]
I change a new server resource to retry it,it works out!Thanks again!
