### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 473021677** [sortmerna/sortmerna#359]
Hi,
I am using sortmerna to remove rRNA from metatranscriptomic clean reads. However, the program terminated abnormally and the error "init_split_file/opt/pbs/dispatcher/mom_priv/jobs/86936.mgmt.SC: line 8: 109391 Segmentation fault      (core dumped)" has been reported. I have ensured no lost whitespace, and no added new line characters corrupt my command line. The command is "/share/home/linanh/softwares/sortmerna-4.3.6/bin/sortmerna --ref /share/home/linanh/database/sortmerna_rRNA/rfam-5.8s-database-id98.fasta --ref /share/home/linanh/database/sortmerna_rRNA/rfam-5s-database-id98.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-arc-16s-id95.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-arc-23s-id98.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-bac-16s-id90.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-bac-23s-id98.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-euk-18s-id95.fasta --ref /share/home/linanh/database/sortmerna_rRNA/silva-euk-28s-id98.fasta --reads JZ-2-M-LDG1360_L6_1_fastp.fq --reads JZ-2-M-LDG1360_L6_2_fastp.fq --workdir ./ --other JZ-2-M-LDG1360_L6_rm_rRNA --aligned JZ-2-M-LDG1360_L6_aligned_rRNA --threads 15 --fastx --paired_in --out2".
I have appended the log file. I really need your help. If you can help, I really appreciate. Thanks very much.

 Best regards,
[sortmerna.log.txt](https://github.com/sortmerna/sortmerna/files/11177516/sortmerna.log.txt)

**Comment by biocodz** [comment]
Looks very much like the directory limits (resource allocation) problem, similar to what was reported here many times e.g. [issue 340](https://github.com/sortmerna/sortmerna/issues/340), [issue 323](https://github.com/sortmerna/sortmerna/issues/323)

**Comment by 473021677** [comment]
Thanks for your reply. I have checked the diretory limits problem by using the command "ulimit -a". It shows like 
"core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514514
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
".
It seems like that there is no limits for resource allocation. What can I do to solve this problem? Thanks very much.

**Comment by 473021677** [comment]
Thanks for your reply. I have checked the diretory limits problem by using the command "ulimit -a". It shows like 
"core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514514
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
".
It seems like that there is no limits for resource allocation. What can I do to solve this problem? Thanks very much.

**Comment by biocodz** [comment]
Without knowing your system, it's hard to tell how the resource allocation is configured. That's the business of a system administrator. But you would have to check the limits on disk space, memory, and CPU. In your case it's likely either memory, or disk limits.

**Comment by 473021677** [comment]
I will contact the system administrator. And what are the limits on memeory and disk space?

Best regards,

**Comment by 473021677** [comment]
I will contact the system administrator. And what are the limits on memeory and disk space?

Best regards,
