### ISSUE TITLE
sortmerna not processing

### ISSUE THREAD

**Issue by YuWang07** [sortmerna/sortmerna#368]
Hi, everyone

I am trying to run sortmerna to filter out the rRNA, but the slurm script was stuck like forever, the command line works when I run it in my home directory. It did not give any error message when I submit the job, any idea is appreciated. Thanks for the help in advance!

The log file:
mkdir: cannot create directory ‘/storage/kaleen/s4519890/Assembly.M2/03_transcriptomics/03_mRNA_reads’: File exists
Starting sortmerna for sample SE8491_S1_R1_001_val_1.fq.gz at Sun Apr 23 10:12:17 AEST 2023
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: /storage/kaleen/s4519890/Assembly.M2/03_transcriptomics/bash/database/smr_v4.3_default_db.fasta of previous flag: --ref
Found flag: --reads
Found value: SE8491_S1_R1_001_val_1.fq.gz of previous flag: --reads
Found flag: --reads
Found value: SE8491_S1_R2_001_val_2.fq.gz of previous flag: --reads
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --workdir
Found value: /storage/kaleen/s4519890/Assembly.M2/03_transcriptomics/03_mRNA_reads/SE8491_S1_work_dir of previous flag: --workdir
Found flag: --aligned
Found value: /storage/kaleen/s4519890/Assembly.M2/03_transcriptomics/03_mRNA_reads/SE8491_S1_work_dir/non-mRNA of previous flag: --aligned
Found flag: --other
Found value: /storage/kaleen/s4519890/Assembly.M2/03_transcriptomics/03_mRNA_reads/SE8491_S1_work_dir/mRNA of previous flag: --other
Found flag: --paired_in
Previous flag: --paired_in is Boolean. Setting to True
Found flag: --out2
Previous flag: --out2 is Boolean. Setting to True
Found flag: -threads
Found value: 16 of previous flag: -threads

**Comment by biocodz** [comment]
The execution hangs even before the option processing is completed. You should work on this with your system administrator. Could be permissions and/or resource allocation problem similar to what was reported many times by HPC/slurm users e.g. [issue 356](https://github.com/sortmerna/sortmerna/issues/356).
Without an access to your system we can only guess here.

**Comment by YuWang07** [comment]
Hi,

Thank you for the information. After a prolonged delay of the first sample(more than 4hrs), it eventually started working smoothly. Although it is currently functioning, I am unsure why this problem occur.
