### ISSUE TITLE
paired end reads become unordered after sortmerna

### ISSUE THREAD

**Issue by linneakh** [sortmerna/sortmerna#369]
I have been having a problem with my paired end reads becoming unordered after sortmerna analysis, which messes up my downstream proceses, such as mapping (I'm interested in my reads that don't map to rRNA databases). Here is my code:

sortmerna -ref ~/software/silva-bac-16s-id90.fasta \
        -ref ~/software/silva-arc-16s-id95.fasta \
        -ref ~/software/silva-arc-23s-id98.fasta \
        -ref ~/software/silva-bac-23s-id98.fasta \
        -ref ~/software/silva-euk-18s-id95.fasta \
        -ref ~/software/silva-euk-28s-id98.fasta \
        -reads ${sample}_bbduck_1.fq.gz \
        -reads ${sample}_bbduck_2.fq.gz \
        -kvdb /out/${sample}/kvdb/ \
        --idx-dir /out/idx/ \
        -readb /out/${sample}/readb/ \
        -aligned /out/${sample}/out/ \
        -other /out/${sample}/out/ \
        -fastx \
        --paired-in \
        --out2 \
        -threads 94

Am I doing something wrong? Others I know have a similar problem, but it seems that many people use this program, so I'd like to know how to correct this.

Thank you!

**Comment by biocodz** [comment]
What Sortmerna version do you use? Can you provide the [trace](https://github.com/sortmerna/sortmerna#execution-trace)?

**Comment by tatyanalivshultz** [comment]
Hi @linneakh. I am also inputting paired end read files as two files and getting a single output file for the --other flag. But when I look at the file contents, I see that it contains paired end reads in interleaved format. What does your output file look like?
@biocodz is there a way to specify that the two reads of a pair should be written to separate files?

@LH00150:7:223HJHLT3:3:1101:20537:2426 1:N:0:ATCATGCG+ATAGAGCG
GAATCTTTTGGCGTCTTNATCAAACCCTTGACTTCAGNTGAAGTAGCTTCATAGATTTCAACAACTTTAGGTTGAAGCTCNGTCTTCTTCTCTTCAAACTCCTTGGNATNTTGC
+
FFFFFFF-FFFFFFFFF#FFFFFFFFFFFFFFFFFFF#F-FFFFFFFFFFFFFFFFF-FFF-FFFFFFFFFFFFF-FFFF#FFFFFFFFF-FF----FFFFFFF-F#FF#FF-F
@LH00150:7:223HJHLT3:3:1101:20537:2426 2:N:0:ATCATGCG+ATAGAGCG
GCAATATTCCAAGNAGTNTGAAGAGAAGAAGACTGAGCTTCAACCTAAAGTTGTCGAAATCTATGAAGCTACTTCAACTGAAGTCAAGGGTTTGATTAAGACGCCCAAAGATTC
+
FFFFFF-FFFFFF#FFF#F-FFFFFFFFFF-FFF-FFFFFF-FFF-FFFFFFFF-FFF-FFFFFFFFFFFFFFFFFF-FFF-FFFFFFFFF--FFFFF-FFFF---FFFF-FFF
@LH00150:7:223HJHLT3:3:1101:7445:3259 1:N:0:ATCATGCG+ATAGAGCG
GGGGTGGAGGTGGAGGTNACTTGTAAGCGTAGGGCGGNGTTGGGTGTGGATACTTGTGGGGTGGAGGTGGAGGTGACTTGNAAGCGTAGGGTGGTGTTGGGTGCGGNTANTTG
+
FFFFFF5-FFFFFFFFF#FFFFF-FFFFFFF-FFFFF#FFFFF--FFFFFFFFFFFFFFFF-FFFFFFFFFFFFF--F--#FF-FFFFFFFFFFFFFFFFFFFFFF#FF#FFF
@LH00150:7:223HJHLT3:3:1101:7445:3259 2:N:0:ATCATGCG+ATAGAGCG
CAAGTATCCGCACNCAANACCACCCTACGCTTACAAGTCACCTCCACCTCCACCCCACAAGTATCCACACCCAACACCGCCCTACGCTTACAAGTCACCTCCACCTCCACCCC
+
FFFFFFFFFFFFF#FFF#FFF-FFFF-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FFFF-FFF-FFFFFFF-FFFFFFFFFFFF-F-FFFFFF-FFF-FFFF-FFFF

**Comment by biocodz** [comment]
@tatyanalivshultz , please have a look at [issue 333](https://github.com/sortmerna/sortmerna/issues/333), the beginning of the last message. It gives some hints on controlling the output that can be produced by sortmerna.

**Comment by slambrechts** [comment]
@linneakh did you solve this? We have the same problem, and I guess this might have something to do with the "LH00150". Is this from a novaseq X plus run?
