### ISSUE TITLE
Database to use for human RNASeq

### ISSUE THREAD

**Issue by Rohit-Satyam** [sortmerna/sortmerna#372]
Which database should we use to remove rRNA from Human RNASeq dataset. I see that using default database `smr_v4.3_default_db.fasta` gives me similar results to what I get using ribodetector. However, when I use `resources/smr_v4.3_sensitive_db_rfam_seeds.fasta` I get more than half of my reads assigned as rRNA. Is there a benchmarking study or some inhouse test that can tell us which one should be used.

**Comment by ppericard** [comment]
Hi @Rohit-Satyam,

We do not expect to have significant differences by using these two databases on Human RNA-seq data.

Would you mind sharing your command line and a few additional information?

What type of library preparation was done (total RNA, mRNA capture, ...) ?
How many reads are there in total? How many were identified as rRNA by ribodetector? How many identified as rRNA using SortMeRNA with the default db? And with the sensitive db?
Could you also give us the results from `ls -l smr_v4.3_default_db.fasta` and `ls -l resources/smr_v4.3_sensitive_db_rfam_seeds.fasta`?

Best regards,
Pierre

**Comment by Rohit-Satyam** [comment]
Yeah sure here are the Details:

RNASeq library: Total RNASeq from the Nasal Swab of COVID patients. Checked for bacterial reads in samples (<1%). 

| Samples | TotalReads | Trim-Survived-Reads | rRNA(Ribodetector) | Useful-reads(Ribodetector) | rRNA(SortmeRna-sensitive_db_rfam) | Useful-reads(SortmeRna-sensitive_db_rfam) | rRNA(SortmeRna-default_db) | Useful-reads(SortmeRna-default_db) |
| ------- | ---------- | ------------------- | ------------------ | -------------------------- | --------------------------------- | ----------------------------------------- | -------------------------- | ---------------------------------- |
| Sample1 | 39668      | 33309               | 3174               | 30135                      | 3783                              | 29526                                     | 3809                       | 29500                              |
| Sample2 | 14825      | 11797               | 493                | 11304                      | 3797                              | 29512                                     | 667                        | 32642                              |

Also note that SortMerna have more Useful-reads(refers to non-rRNA reads ) than the trimmed reads given as an input for Sample2 (I don't understand why coz when I add `rRNA(SortmeRna-default_db)` and `Useful-reads(SortmeRna-default_db)` or  ` rRNA(SortmeRna-sensitive_db_rfam)` and `Useful-reads(SortmeRna-sensitive_db_rfam)` they don't add up for sample2). Somehow sortmerna increases number of Useful reads which is strange.

The Nextflow Process block is as follows


```
process RIBODETECTOR{
publishDir "${params.outdir}/rRNA/ribodetector", mode: 'copy'
        input:
                //tuple val(sid), path(reads)
                tuple val(sid), path(reads0), path(reads1)

        output:
                tuple val(sid), path("*.fq.gz")
                path("*.txt")

        shell:
'''
mean_len=$(bioawk -c fastx '{sum += length($seq)} END {printf "%d", sum / NR}' !{reads0})

ribodetector_cpu -t !{task.cpus} -l ${mean_len} -i !{reads0} !{reads1} -e rrna \
-r !{sid}.rrna_ribodetector.R1.fq !{sid}.rrna_ribodetector.R2.fq --chunk_size 256 \
-o !{sid}.clean_ribodetector.R1.fq !{sid}.clean_ribodetector.R2.fq

raw=$(zcat !{reads0}  | wc -l | awk '{print $1/4}')
rrna=$(wc -l !{sid}.rrna_ribodetector.R1.fq | awk '{print $1/4}')
nonrRNA=$(wc -l !{sid}.clean_ribodetector.R1.fq | awk '{print $1/4}')

echo !{sid},$raw,$rrna,$nonrRNA > !{sid}_ribodetector_results.txt
gzip !{sid}.rrna_ribodetector.R1.fq
gzip !{sid}.rrna_ribodetector.R2.fq
gzip !{sid}.clean_ribodetector.R1.fq
gzip !{sid}.clean_ribodetector.R2.fq
'''
}


process SORTMERNA{
publishDir "$params.outdir/rRNA/sortmerna", mode: 'copy'

        input:
                //tuple val(sid), path(reads)
                tuple val(sid), path(reads0), path(reads1)

        output:
                tuple val(sid), path("*.fq.gz")
                path("*.log")
                path("*.txt")

        shell:
'''
sortmerna !{params.sortmerna_ext} --reads !{reads0} --reads !{reads1} --fastx --threads !{task.cpus} \
--paired_out --out2 --aligned !{sid}.rrna_sortmerna --other !{sid}.clean_sortmerna --kvdb temp/kvdb

mv !{sid}.rrna_sortmerna_fwd.fq.gz !{sid}.rrna_sortmerna.R1.fq.gz
mv !{sid}.rrna_sortmerna_rev.fq.gz !{sid}.rrna_sortmerna.R2.fq.gz
mv !{sid}.clean_sortmerna_fwd.fq.gz !{sid}.clean_sortmerna.R1.fq.gz
mv !{sid}.clean_sortmerna_rev.fq.gz !{sid}.clean_sortmerna.R2.fq.gz

raw=$(zcat !{reads0}  | wc -l | awk '{print $1/4}')
rrna=$(zcat !{sid}.rrna_sortmerna.R1.fq.gz | wc -l | awk '{print $1/4}')
nonrRNA=$(zcat !{sid}.clean_sortmerna.R1.fq.gz | wc -l | awk '{print $1/4}')

echo !{sid},$raw,$rrna,$nonrRNA > !{sid}_sortmerna_results.txt
rm -rf temp
'''
}

workflow{

}
```

**Comment by ppericard** [comment]
The results are indeed quite unusual.
However, I cannot tell if the problem comes from SortMeRNA or the Nextflow pipeline.
In your table, the numbers from Sample2 add up to the total number of reads in Sample1. This leads me to believe there could be confusion between the two samples because of cache or erroneous input redirection in the pipeline.
To eliminate any possible bug from the Nextflow pipeline, could you manually run the 4 SortMeRNA filtering steps, outside the pipeline, in fresh directories each time?

**Comment by Rohit-Satyam** [comment]
Hi @ppericard Yes when I run one sample at a time then I get correct number of the reads. I use the same command as I am using in Nextflow so I don't understand why it happens. How do you think can I overcome this?

**Comment by biocodz** [comment]
Would it be possible to provide the [execution trace](https://github.com/sortmerna/sortmerna#execution-trace)?
