### ISSUE TITLE
Read deflation error(sortmeRNA 4.3.4)

### ISSUE THREAD

**Issue by KonstanzeTan** [sortmerna/sortmerna#386]
**Describe the bug**
Dear sortmeRNA developers,

While running sortmeRNA (version 4.3.4) using paired-end gzip files, I get the following error message when specifiying 10 threads to split my files. In my sample execution trace included, the job halts at: 

/home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_2.fq.gz for reading

and does not proceed to open the other (8) split read files for reading. The error message returned is: 

[write_a_read:214] ERROR: Failed deflating readstring: 
[write_a_read:214] ERROR:  zlib status: -1

I am running this job on HPC (24 CPUs, requested memory of 12gb). 

**Sample execution trace (with file paths modified)*
[process:1376] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: /home/users/12xxxx/username/RNAseq_proj/sortmerna_db/smr_v4.3_default_db.fasta of previous flag: --ref
Found flag: --reads
Found value: RNA10318_1_val_1.fq.gz of previous flag: --reads
Found flag: --reads
Found value: RNA10318_2_val_2.fq.gz of previous flag: --reads
Found flag: --aligned
Found value: /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned of previous flag: --aligned
Found flag: --other
Found value: /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/filtered/RNA10318_filtered of previous flag: --other
Found flag: --paired_in
Previous flag: --paired_in is Boolean. Setting to True
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --num_alignments
Found value: 1 of previous flag: --num_alignments
Found flag: --workdir
Found value: /home/users/institute/user001/scratch/sortmerna/RNA10318 of previous flag: --workdir
Found flag: --idx-dir
Found value: /home/users/institute/user001/scratch/sortmerna/idx of previous flag: --idx-dir
Found flag: --out2
Previous flag: --out2 is Boolean. Setting to True
Found flag: --threads
Found value: 10 of previous flag: --threads
[opt_workdir:994] Using WORKDIR: "/home/users/institute/user001/scratch/sortmerna/RNA10318" as specified
[process:1460] Processing option: aligned with value: /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned
[process:1460] Processing option: fastx with value: 
[process:1460] Processing option: idx-dir with value: /home/users/institute/user001/scratch/sortmerna/idx
[opt_idxdir:1018] Using IDX dir: ["/home/users/institute/user001/scratch/sortmerna/idx" as specified
[process:1460] Processing option: num_alignments with value: 1
[process:1460] Processing option: other with value: /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/filtered/RNA10318_filtered
[process:1460] Processing option: out2 with value: 
[process:1460] Processing option: paired_in with value: 
[process:1460] Processing option: reads with value: RNA10318_1_val_1.fq.gz
[opt_reads:97] Processing reads file [1] out of total [2] files
[process:1460] Processing option: reads with value: RNA10318_2_val_2.fq.gz
[opt_reads:97] Processing reads file [2] out of total [2] files
[process:1460] Processing option: ref with value: /home/users/12xxxx/username/RNAseq_proj/sortmerna_db/smr_v4.3_default_db.fasta
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:205] File "/home/users/12xxxx/username/RNAseq_proj/sortmerna_db/smr_v4.3_default_db.fasta" exists and is readable
[process:1460] Processing option: threads with value: 10
[process:1480] === Options processing done ===
[process:1481] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1227] Key-value DB location "/home/users/institute/user001/scratch/sortmerna/RNA10318/kvdb"
[validate_kvdbdir:1263] Creating KVDB directory: "/home/users/institute/user001/scratch/sortmerna/RNA10318/kvdb"
[validate_idxdir:1193] Using index directory: "/home/users/institute/user001/scratch/sortmerna/idx"
[validate_idxdir:1209] IDX directory: "/home/users/institute/user001/scratch/sortmerna/idx" exists and is not empty
[validate_readb_dir:1285] Using split reads directory : "/home/users/institute/user001/scratch/sortmerna/RNA10318/readb"
[validate_readb_dir:1293] Created split reads directory - OK
[main:62] Running command:
sortmerna --ref /home/users/12xxxx/username/RNAseq_proj/sortmerna_db/smr_v4.3_default_db.fasta --reads RNA10318_1_val_1.fq.gz --reads RNA10318_2_val_2.fq.gz --aligned /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned --other /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/filtered/RNA10318_filtered --paired_in --fastx --num_alignments 1 --workdir /home/users/institute/user001/scratch/sortmerna/RNA10318 --idx-dir /home/users/institute/user001/scratch/sortmerna/idx --out2 --threads 10 
[Index:102] Found 4 non-empty index files. Skipping indexing.
[init:108] Readfeed init started
[define_format:915] file: "RNA10318_1_val_1.fq.gz" is FASTQ gzipped
[define_format:915] file: "RNA10318_2_val_2.fq.gz" is FASTQ gzipped
[count_reads:949] started count  ...   
[next:322] EOF FWD reached. Total reads: 39903900
[next:322] EOF REV reached. Total reads: 39903900
[count_reads:979] done count. Elapsed time: 348.388 sec. Total reads: 79807800
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_0.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_0.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_1.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_1.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_2.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_2.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_3.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_3.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_4.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_4.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_5.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_5.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_6.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_6.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_7.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_7.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_8.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_8.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/fwd_9.fq.gz
[init_split_files:1001] added file: /home/users/institute/user001/scratch/sortmerna/RNA10318/readb/rev_9.fq.gz
[split:605] start splitting. Using number of splits equals number of processing threads: 10
[next:322] EOF FWD reached. Total reads: 39903900
[next:322] EOF REV reached. Total reads: 39903900
[split:717] Done splitting. Reads count: 79807800 Runtime sec: 4954.52

[init:135] Readfeed init done in sec [5302.97]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 79807800 all_reads_len= 11921068541 min_read_len= 150 max_read_len= 108 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 24
[align:163] Using number of Processor threads: 10
[Refstats:60] Index Statistics calculation starts ... done in: 0.67678 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 10 ... 
[align:190] done in [6.18369] sec Memory KB: 3189
[align:193] Loading references ...
[align:197] done in [0.52496] sec. Memory KB: 3345
[align2:70] Processor 2 thread 46914494056192 started
[align2:70] Processor 0 thread 46914498258688 started
[align2:70] Processor 1 thread 46914496157440 started
[align2:70] Processor 8 thread 46914481448704 started
[align2:70] Processor 4 thread 46914489853696 started
[align2:70] Processor 5 thread 46914487752448 started
[align2:70] Processor 6 thread 46914485651200 started
[align2:70] Processor 9 thread 46914479347456 started
[align2:70] Processor 3 thread 46914491954944 started
[align2:70] Processor 7 thread 46914483549952 started
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 4 thread 46914489853696 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1052325 Runtime sec: 4528.86
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 3 thread 46914491954944 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1049704 Runtime sec: 4534.04
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 6 thread 46914485651200 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1040436 Runtime sec: 4571.5
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 0 thread 46914498258688 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1041938 Runtime sec: 4573.36
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 9 thread 46914479347456 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1046239 Runtime sec: 4585.47
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 2 thread 46914494056192 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1046657 Runtime sec: 4585.9
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 5 thread 46914487752448 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1039516 Runtime sec: 4602.53
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 7 thread 46914483549952 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1043098 Runtime sec: 4634.06
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 8 thread 46914481448704 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1045059 Runtime sec: 4637.4
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[align2:133] Processor 1 thread 46914496157440 done. Processed 7980780 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1044384 Runtime sec: 4681.76
[align:220] done index: 0 part: 1 in 4681.76 sec Memory KB: 6593
[align:227] Index and References unloaded in 1.12327 sec. Memory KB: 6593
[align:237] ==== Done alignment in 4689.59 sec ====

[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 79807800 all_reads_len= 11921068541 min_read_len= 150 max_read_len= 108 total_aligned= 10449356 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[writeSummary:179] ==== Starting summary of alignment statistics ====
[Refstats:60] Index Statistics calculation starts ... done in: 0.767439 sec
[write:62] Using summary file: /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned.log
[writeSummary:185] ==== Done summary in sec [0.774136] ====

[writeReports:169] === Report generation starts ===
[writeReports:184] Restored Readstats from DB: 1
[Refstats:60] Index Statistics calculation starts ... done in: 0.668794 sec
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
           +        +       +                      +           +     2e
[set_num_out:162] num_out: 2
[init:60] num_out: 2
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
           +        +       +                      +           +     2e
[set_num_out:162] num_out: 2
[init:60] num_out: 2
[writeReports:199] loading reference 0 part 1/1 ... done in 0.48508 sec
[report:93] Report Processor: 6 thread: 46914491954944 started. Memory KB: 3974
[report:93] Report Processor: 2 thread: 46914483549952 started. Memory KB: 3974
[report:93] Report Processor: 9 thread: 46914498258688 started. Memory KB: 3974
[report:93] Report Processor: 8 thread: 46914496157440 started. Memory KB: 3974
[report:93] Report Processor: 3 thread: 46914485651200 started. Memory KB: 3974
[report:93] Report Processor: 7 thread: 46914494056192 started. Memory KB: 3974
[report:93] Report Processor: 4 thread: 46914487752448 started. Memory KB: 3974
[report:93] Report Processor: 1 thread: 46914481448704 started. Memory KB: 3974
[report:93] Report Processor: 0 thread: 46914479347456 started. Memory KB: 3974
[report:93] Report Processor: 5 thread: 46914489853696 started. Memory KB: 3974
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 9 thread: 46914498258688 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 2 thread: 46914483549952 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 6 thread: 46914491954944 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 0 thread: 46914479347456 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 4 thread: 46914487752448 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 3 thread: 46914485651200 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 7 thread: 46914494056192 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 1 thread: 46914481448704 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 5 thread: 46914489853696 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[next:455] EOF FWD reached. Total reads: 3990390
[next:455] EOF REV reached. Total reads: 3990390
[report:152] Report processor: 8 thread: 46914496157440 done. Processed reads: 7980780 Invalid reads: 0 Memory KB: 4006
[writeReports:220] done reference 0 part: 1 in 167.06 sec
[writeReports:226] references unloaded in 0.0206334 sec Memory KB: 4006
[openfr:129] Opened output file /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_1.fq.gz for reading.
[merge:83] merged /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_1.fq.gz -> /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_0.fq.gz
[merge:90] deleted /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_1.fq.gz
[openfr:129] Opened output file /home/users/12xxxx/username/RNAseq_proj/results/3_rRNA/aligned/RNA10318_aligned_fwd_2.fq.gz for reading.

**Version **
sortmeRNA 4.3.4

Your advice on how best I can resolve this issue is much appreciated. 

Thank you.

**Comment by biocodz** [comment]
I would advise to switch to the latest 4.3.6 version. A few bugs were fixed since 4.3.4.
