### ISSUE TITLE
Removal of rRNA causes uneven reads

### ISSUE THREAD

**Issue by lilyyycao** [sortmerna/sortmerna#390]
Hello,

I have ran sortmerna on some interleaved FASTQ files and noticed that after running sortmerna, my FASTQ files do not have the correct number of paired reads (ie, doing a quick check on how many times 0:N and 1:N appears shows that 0:N shows up 10327564 while 1:N shows up only 9745851 times). I am wondering how to go about fixing this as I had expected both of these to show up an equal number of times being an interleaved FASTQ file. Was there supposed to be a parameter I had to add indicating these are interleaved FASTQ files?

The following code is what I ran to output my ribodepleted file:

./sortmerna --ref /Users/lyc5319/Desktop/RNA_Processing/sortmerna-2.1/database/smr_v4.3_fast_db.fasta,/Users/lyc5319/Desktop/RNA_Processing/sortmerna-2.1/database/smr_v4.3_fast_db.idx --reads /Users/lyc5319/Desktop/RNA_Processing/sortmerna-2.1/TRIM/TRIM_9R.FASTQ --num_alignments 1 -m 15000 -a 3 --fastx --aligned /Users/lyc5319/Desktop/RNA_Processing/sortmerna-2.1/TRIM/9R.ribosomes --other /Users/lyc5319/Desktop/RNA_Processing/sortmerna-2.1/TRIM/9R.ribodepleted

Thank you!

**Comment by biocodz** [comment]
2.1 is quite a dated version. Numerous fixes were applied since. The latest version is [4.3.6](https://github.com/sortmerna/sortmerna/releases/tag/v4.3.6)

**Comment by ppericard** [comment]
Hi @lilyyycao,
Unfortunately, SortMeRNA cannot handle interleaved paired-end FASTQ files as of the latest version. Which means they are dealt with like single-end files.
As with most modern bioinformatics tools, we recommend using separate paired-end files such as `forward_reads.fq.gz` and `reverse_reads.fq.gz`.
As a workaround right now with your files, you have two solutions:
1. Split **before running SortMeRNA** your interleaved file into two files using either native bash (https://stackoverflow.com/questions/59633038/how-to-split-paired-end-fastq-files) or a dedicated tool (https://ngsutils.org/modules/fastqutils/split/)
2. Run SortMeRNA by inputting your interleaved file as a single-end file and then extract the singleton reads using a custom script
I recommend the first solution.
I hope this helps!

**Comment by lilyyycao** [comment]
Hi, thank you for your reply back. I am wondering can the newest version compatible with Mac OS or is only for Linux? I will go ahead and try to re-run using the newest version with separate paired-end files.

**Comment by ppericard** [comment]
Unfortunately, we dropped Mac OS support since v3. We may support it again in the future, but for now, we are focussing on providing the best user experience for installation and usage on Linux machines. Therefore, I recommend using a Linux machine or if you have access to an HPC infrastructure such as a computing cluster or cloud.

**Comment by ppericard** [comment]
Also, so you have all the information, using SortMeRNA v2.1 or v2.1b, you could use the options `--paired_in` or `--paired_out` to be sure to get an interleaved paired-file as output.

**Comment by biocodz** [comment]
Sortmerna has option `--paired` to indicate the reads file contains interleaved reads

**Comment by lilyyycao** [comment]
Thank you, I will see if I am able to run this on linux, at the moment I only have an access to a Mac. Will that cause major issues if I proceed using V 2.1?

> Also, so you have all the information, using SortMeRNA v2.1 or v2.1b, you could use the options `--paired_in` or `--paired_out` to be sure to get an interleaved paired-file as output.
> Sortmerna has option `--paired` to indicate the reads file contains interleaved reads

Thank you, I will go ahead and add the --paired_in/out option as I think that was the issue with having unequal paired reads in my output files. Along with that, should i indicated --paired instead of --reads using v 2.1 or is this flag only for later versions of sortmerna?

**Comment by ppericard** [comment]
@biocodz, yep... My bad.... I was looking at an earlier 4.x version....
So @lilyyycao you then have many options, either run SortMeRNA 2.1 with `--paired_in` or `--paired_out` options, or use the latest version with your interleaved file while activating the `--paired` option **and** the `--paired_in` or `--paired_out` options, or split your file and give them to SortMeRNA as input by using the `--reads` option twice.

**Comment by ppericard** [comment]
@lilyyycao , I'm speaking under @biocodz control, but I think the `--paired` option was introduced in one of the latest version and does not exist in v2.1.
As for running v2.1, it is still a highly used version, and we do not expect major errors with the results, especially if you are only using it for filtering.

**Comment by lilyyycao** [comment]
Hi, i just wanted to update that using the --paired option corrected the issue, thank you!
