### ISSUE TITLE
ERROR: Sequence length > 30000 nt

### ISSUE THREAD

**Issue by orbitalse** [sortmerna/sortmerna#402]
Hello,

I have been using sortmeRNA for a while now to identify and remove rRNAs from long-read Minion sequencing data. I noticed that sortmeRNA throws an error when read lengths are longer than 30kb. An example of the errors I received is below:

```
[validate:291] ERROR: Read ID: 22_16 Header: @902c2b97-5232-4e75-b48f-b23bfa9dc0a8 runid=475feb7b5b097be8af56cd67202c28731961b349 read=27640 ch=143 start_time=2023-08-03T19:56:07.868182-04:00 flow_cell_id=FAW09659 protocol_group_id=LigationSequencingKit sample_id=thermotubes_flepseq parent_read_id=902c2b97-5232-4e75-b48f-b23bfa9dc0a8 basecall_model_version_id=dna_r10.4.1_e8.2_5khz_400bps_hac@v4.2.0 **Sequence length: 205637 > 30000 nt** 
  Please check your reads or contact the authors.
/var/spool/slurm/job13130024/slurm_script: line 56: 3583596 Segmentation fault      (core dumped) 
```

Is there a way to bypass this error? sortmeRNA is an important part of our QC pipeline but I end up losing a bunch of reads whenever this error is thrown. I'd like to keep them in my data, especially since these > 30kb reads are exactly what we want but are quite difficult to obtain.

Many thanks in advance.

**Comment by cmith44** [comment]
Hi, as mentioned in #373, SortMeRNA isn't designed or optimized for filtering or aligning long reads, and this 30000nt is a limit set in previous versions. Since this is a duplicate issue, I'm going to close it. Feel free to discuss or ask questions this in the #373 issue.
