### ISSUE TITLE
v4.3.6 gets killed when processing large paired-end files

### ISSUE THREAD

**Issue by Catv97** [sortmerna/sortmerna#405]
**Describe the bug**
I´m trying to run sortmerna 4.3.6 on paired end samples, where each gz file is around 4Gb. I have available 40 CPUs and 250Gb of memory. After trying to run this overnight it gets killed and it seems due to large memory usage. The command I used is this:
sortmerna --ref /home/databases/SILVA/eukaryota_ALLref_silva138.1.fasta  --reads /home/projects/ossabaw/samples/SRP413590_yaolei/trimmed/SRR22799305_TRIM_1P.fastq.gz --reads /home/projects/ossabaw/samples/SRP413590_yaolei/trimmed/SRR22799305_TRIM_2P.fastq.gz --workdir . --fastx --aligned /home/projects/ossabaw/samples/SRP413590_yaolei/rRNA --other /home/projects/ossabaw/samples/SRP413590_yaolei/norRNA --paired_out  --out2 -threads 13.

**Screenshots**
<img width="1494" alt="Screenshot 2023-10-25 at 09 17 17" src="https://github.com/sortmerna/sortmerna/assets/126099697/75018918-8eb1-43c0-a655-57db4707d540">

Is there anything else I can try?

Thanks!
Catarina

**Comment by biocodz** [comment]
Could be a resource allocation problem reported here many times, see e.g. [issue 355](https://github.com/sortmerna/sortmerna/issues/355), or search issues using `'allocation'` keyword.
You would have to check the limits (directory size, memory, cpu etc.) with your sysadmin
