### ISSUE TITLE
SAM output - gzip compression invalid?

### ISSUE THREAD

**Issue by MicroSeq** [sortmerna/sortmerna#408]
SortMeRNA version 4.3.6
Build Date: Aug 16 2022

Hello, 

I am attempting to work with the alignments from our dataset output into .sam format. It appears that the compression being used is corrupting the output. I attempted to set the zip-output flag to 0 and it appears sortmerna still compresses the output anyways. 

file on the output shows that the method is listed as unknown: 

zip compressed data, from Unix, original size modulo 2^32 1073558160 gzip compressed data, unknown method, ASCII, extra field, has comment, encrypted, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 1073558160

gunzip shows:  invalid compressed data--format violated

The files still seem to work with samtools view, but will fail conversion to bam with the following error:

[E::inflate_gzip_block] Inflate operation failed: invalid block type
[E::bgzf_read_block] Reading GZIP stream failed at offset 51244800

**Comment by sonal-res** [comment]
I get similar error: `invalid compressed data--crc error` and `invalid compressed data--length error`

**Comment by MicroSeq** [comment]
> could you, please, provide the [trace](https://github.com/sortmerna/sortmerna#execution-trace)

Trace is attached. Let me know if I can provide anything else.

[trace1.log](https://github.com/sortmerna/sortmerna/files/13555088/trace1.log)

**Comment by biocodz** [comment]
@MicroSeq thanks for the input.

Looks like a bug. We have a few tests with SAM output e.g. [test 37](https://github.com/sortmerna/sortmerna/blob/master/scripts/test.jinja#L2728). Just tried it on Win11 and `6.2.0-37-generic #38~22.04.1-Ubuntu`. Worked OK on Win but showed the error on Lin
```
zless run/out/aligned.sam.gz
   gzip: run/out/aligned.sam.gz: invalid compressed data--format violated

zless run/out/aligned.blast.gz  <- OK (strange as the same routine is used for compression)
```
I'll try to fix this fast

**Comment by biocodz** [comment]
the bug was fixed and tested. Currently in branch [build_3rdparty](https://github.com/sortmerna/sortmerna/tree/build_3rdparty), and awaiting completion of [enhancement 410](https://github.com/sortmerna/sortmerna/issues/410)

**Comment by biocodz** [comment]
fixed in release [4378](https://github.com/sortmerna/sortmerna/releases/tag/v4.3.7)
