### ISSUE TITLE
Error when try to run SMR in parallel

### ISSUE THREAD

**Issue by Morpheus2112** [sortmerna/sortmerna#409]
Hello there,

It's me again, I want to report a bug when I tried to run SRM in parallel on a HPC.

Here is the screenshot. 

The version is 4.3.6.

Any suggestion would be very helpful.

Thanks a lot.

Best,
JZ
[截屏2023-12-27 16.44.55.pdf](https://github.com/sortmerna/sortmerna/files/13779652/2023-12-27.16.44.55.pdf)

**Comment by biocodz** [comment]
It's not possible to figure out much from the screenshot. But quite likely it could be the problem with the HPC setup like allocation of memory, disk, threads, processes, access permissions etc. You can find quite a few such issues reported here using keywords like ['allocation'](https://github.com/sortmerna/sortmerna/issues?q=is%3Aissue+allocation) or ['limits'](https://github.com/sortmerna/sortmerna/issues?q=is%3Aissue+limits)
