### ISSUE TITLE
Segmentation fault while splitting

### ISSUE THREAD

**Issue by jackieway** [sortmerna/sortmerna#411]
Hello, this is a continuation of a comment on made on an earlier issue https://github.com/sortmerna/sortmerna/issues/326#issuecomment-1894676831 . I ran the program again on a different sample with a smaller number of reads (still paired end reads from RNA-seq, adapters and low quality bases trimmed using Cutadapt on Galaxy) using 8 threads. I'm still getting an uneven number of total count of reads, why is this not normal and what could be causing this? I am very new to bioinformatics and am still learning on how to work with RNA-seq data. I've attached the trace below, I still encountered the same segmentation fault error during splitting.

[sortmerna trace segmentation fault smaller.txt](https://github.com/sortmerna/sortmerna/files/13965838/sortmerna.trace.segmentation.fault.smaller.txt)

I am using WSL on my own computer and it reports 730 gb free when I run `df -h`, which I realized is the size remaining on its virtual disk. Even still, my windows C:\ drive reports 30 GB free, and I wouldn't expect the 2 reads (1.58 GB total) to require so much additional space. What could be causing the segmentation fault?

**Comment by biocodz** [comment]
If you are on Windows, you can use Windows executable [sortmerna-4.3.6-win64.7z](https://github.com/sortmerna/sortmerna/releases/download/v4.3.6/sortmerna-4.3.6-win64.7z)
I had problems with WSL in the past, so not using it anymore. VBox worked much better for me.

**Comment by jackieway** [comment]
I tried using the Windows executable instead, and ended up with the following trace, I think the program got stuck somewhere during alignment. Here is the trace file: 
[sortmerna log file command prompt 917 am 1-18-24.txt](https://github.com/sortmerna/sortmerna/files/13978843/sortmerna.log.file.command.prompt.917.am.1-18-24.txt)

I stopped the program because it was running for over 10 hours and was unable to move past `[align2:135] Processor 7 thread 48656 done. Processed 1 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 0 Runtime sec: 88.1882` . Additionally, I think something went wrong starting from `[next:455] EOF REV reached. Total reads: 1
` , since it only picked up 1 read.

**Comment by biocodz** [comment]
Here is a description of a normally running process (apropos 10 hours waiting)  [execution-trace](https://github.com/sortmerna/sortmerna#execution-trace).
When I advised running with smaller files, I meant <= 10k reads, but you can use 100 reads just fine to get a handle on the program usage. Also 1 or 2 reference files instead of 8 to save time. Here for example [test.jinja](https://github.com/sortmerna/sortmerna/blob/master/scripts/test.jinja) are tests used during development.
I would use local files instead of network shares while learning.
You can monitor resource usage on windows using native win utility 'resource monitor', just type 'start -> resource' and it will prompt.

**Comment by jackieway** [comment]
I unfortunately don't have any files with <= 10k reads, all of my samples are metatranscriptome RNA-seq data and have millions of reads. The files are stored on WSL and are not network shares. When I open the resource monitor, nothing looks suspicious and I don't seem to be running out of disk space or RAM. I reran the same command but with 1 reference file (`rRNA_databases_v4\smr_v4.3_default_db.fasta`) instead of the 4 reference files I'd been using, below is the new trace file. Are the last 5 lines a concern? All the sample traces I've looked at have more than just 0 or 1 reads processed (usually thousands) at this point, but mine still say "Processed 0 reads." or "Processed 1 reads".

[sortmerna trace 1 ref.txt](https://github.com/sortmerna/sortmerna/files/13981997/sortmerna.trace.1.ref.txt)
