### ISSUE TITLE
`gcc-13` build failure: `kseq_load.hpp:63:12: error: 'uint64_t' has not been declared`

### ISSUE THREAD

**Issue by trofi** [sortmerna/sortmerna#412]
**Describe the bug**
Attempt to build on `gcc-13` fails as:

```
sortmerna> [ 64%] Building CXX object src/sortmerna/CMakeFiles/smr_objs.dir/kseq_load.cpp.o
sortmerna> In file included from /build/sortmerna/src/sortmerna/kseq_load.cpp:39:
sortmerna> /build/sortmerna/include/kseq_load.hpp:63:12: error: 'uint64_t' has not been declared
sortmerna>    63 |            uint64_t number_total_read,
sortmerna>       |            ^~~~~~~~
sortmerna> /build/sortmerna/src/sortmerna/kseq_load.cpp:53:12: error: 'uint64_t' has not
 been declared
sortmerna>    53 |            uint64_t number_total_read,
sortmerna>       |            ^~~~~~~~
sortmerna> make[2]: *** [src/sortmerna/CMakeFiles/smr_objs.dir/build.make:160: src/sortmerna/CMakeFiles/smr_objs.dir/kseq_load.cpp.o] Error 1
```

**Expected behavior**
Build should succeed.

**Additional context**
`gcc-13` cleaned `<string>` includes up and exposed missing `<cstdint>` includes in downstream projects.

**Comment by biocodz** [comment]
Currently only `gcc<=11.4.0` can be used as mentioned [here](https://sortmerna.readthedocs.io/en/latest/building.html#building-on-linux) and [here in conda-recipe waiting for PR approval](https://github.com/biocodz/staged-recipes/blob/sortmerna/recipes/sortmerna/conda_build_config.yaml) ([conda recipe PR 25438](https://github.com/conda-forge/staged-recipes/pull/25438])). 
This is due bugs in 3rd party libraries that rely on upstream  code for includes. We are aware of this and working on the fix. 
For reference, using conda-build allows for easy installation of sandboxed compilers of different versions.
