### ISSUE TITLE
running SortMeRNA jobs in parallel

### ISSUE THREAD

**Issue by Mathildebd** [sortmerna/sortmerna#413]
I might be very wrong, having limited programing skills, but when running the 'new' SortMeRNA v. 4.3.6 versus the (apparently super old) version I normally run v. 2.1, it does not seem possible to run jobs in parallel due to the need for the kvdb DIR to be emptied between each run. So, only by defining a unique work dir per job one could run paralel jobs, but that would mean generating new database index files at each new run, which seems very sub-optimal.... Is there some obvious solution I haven't realized? I would be greatful for help.

**Comment by bug1303** [comment]
New user here as well, who has been fighting with the same issue last week. I think there is currently no way around sample/job-specific work dirs for kvdb/reads/out, but you can create the index once and re-use it. See `sortmerna -h` and  search for index.

**Comment by K0nuci** [comment]
Also new user here,
I made my parallel runs by creating a very small fastq file first and making an index on it.
Afterward for each sample, I specified its specific directories. Below are parts of my code regarding this issue.

              --reads "$R" \
              --other "${R}_norRNA"
              --kvdb "$R" \
              --readb "$R \
              --aligned "${R}_rRNA" \
              -index 0 <- This means skip indexing. If the index does not exist, the program will terminate and warn to build the index 
                                before performing the alignment

in that case, there should be no issue with kvdb as each run has its own
