### ISSUE TITLE
Troubles getting the sorted fastq files

### ISSUE THREAD

**Issue by ManuelAOS** [sortmerna/sortmerna#418]
Hello!

I am trying to use sortmerna in a server that uses condor to filter ribosomal reads from metatranscriptomic data but I have not been able to generate all the filtered files.

I am using sortmerna 4.3.6

The code that I am using is

#!/bin/bash

source ~/miniconda3/etc/profile.d/conda.sh

conda activate /srv/home/mochoa/miniconda3/envs/sortmerna_env

for file in *_host_human_removed__host_penguin_removed_R1.fastq.gz
do
        n=${file%%_host_human_removed__host_penguin_removed_R1.fastq.gz}

 sortmerna --ref silva-bac-16s-id90.fasta --ref silva-bac-23s-id98.fasta --reads ${n}_host_human_removed__host_penguin_removed_R1.fastq.gz --reads ${n}_host_human_removed__host_penguin_removed_R2.fastq.gz --fastx --other ${n}_out_sortmerna --threads 40
done

I understand that the results will be generated in /sortmerna/run/, given that I have 13 paired files I set --other ${n}_out_sortmerna so I could get a directory for each pair of files.

However, I have not been able to produce all the files, rather I end only with one directory. Inside sortmerna/run/out there are some files about the alignment, but only for the first pair of files.

Is there a way to optimize the code given above so I could perform filtering from all files at once?

Besides directory kvdb, is it needed to erase content from other directories before running again sortmerna (e.g., idx readb, etc.)?

Thanks for the help! Very appreciated :)

Manuel

**Comment by biocodz** [comment]
As I understand you are trying to process multiple files in a loop i.e. not a parallel processing.
In this case you can change locations of any working directories on each run/loop. 
Use `--aligned`, `--other` for modifying the output location
`--kvdb` for the key-value database location
`--readb` for the reads pre-processing directory
`--idx-dir` for the index location (note that index can be re-used i.e. needs to be generated only once.)
You can end-up with something like e,g,
```
<workdir>
     idx
     idx1      <- not necessary but possible
     idx2      <- not necessary but possible
     kvdb1   <- or just purge and reuse this location prior each run (the content is unique for each run)
     kvdb2
     kvdb3
     readb1  <- or just purge and reuse (the content is unique for each run)
     readb2
     readb3
     out1
     out2
     out3
```
You also can just rename the directories after each run like  `mv out out1`

**Comment by ManuelAOS** [comment]
Hello @biocodz!

Thanks a lot for your feedback, your answer helped me a lot to better understand sortmerna!

Best regards

Manuel
