### ISSUE TITLE
Clarifying sortmerna output files

### ISSUE THREAD

**Issue by maggieweng** [sortmerna/sortmerna#420]
Hi there, 
Could you please clarify what the expected output files for running this pipeline are?
I see that in the "readb" folder there are four files labeled fwd_0, fwd_1, rev_0, and rev_1 but I am unsure what they represent. Which are the reads that aligned to RNA sequences and which are the reads that did not align? The 'readfeed' text file is not helpful in clarifying this. 

Thanks!

**Comment by biocodz** [comment]
The output files are to be found in `WORKDIR/out/aligned` (default, see `--aligned` option).
See `sortmerna --help` for other options controlling the output, especially `--other`, `--paired`, `--paired_in`, `--paired_out`, `--out2`, `--sout`, `--zip-out`.
[test.jinja](https://github.com/sortmerna/sortmerna/blob/master/scripts/test.jinja) lists a lot of use cases. The file is plain text and should be easily understood. Many tests have `validate` section listing/testing the expected output e.g. [test.jinja line 1297](https://github.com/sortmerna/sortmerna/blob/master/scripts/test.jinja#L1297)

**Comment by maggieweng** [comment]
Ah I think I forgot to add the --aligned flag, I now understand the organization a bit better! It would be great if you could include some more example outputs in the documentation for future reference, particularly with the different output format options. Thanks!
