### ISSUE TITLE
[BUG] Sortmerna 4.3.7 on bioconda channel is corrupt 

### ISSUE THREAD

**Issue by rpeguil** [sortmerna/sortmerna#423]
**Describe the bug**
I have installed SortMeRna following the instructions, but the command "sortmerna" is not recognized.

**To Reproduce**
I follow the instructions to install SortMeRna:
```
conda create -n sortmerna_env
conda activate sortmerna_env
conda install sortmerna
```
And all seem to work:
```
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/odin/anaconda3/envs/sortmerna_env

  added / updated specs:
    - sortmerna


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  brotli-python      conda-forge/linux-64::brotli-python-1.1.0-py312h30efb56_1 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-hd590300_5 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.6.2-hbcca054_0 
  certifi            conda-forge/noarch::certifi-2024.6.2-pyhd8ed1ab_0 
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 
  idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0 
  jinja2             conda-forge/noarch::jinja2-3.1.4-pyhd8ed1ab_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-hf3520f5_7 
  libexpat           conda-forge/linux-64::libexpat-2.6.2-h59595ed_0 
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h77fa898_10 
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h77fa898_10 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.46.0-hde9e2c9_0 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-hc0a3c3a_10 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
  libzlib            conda-forge/linux-64::libzlib-1.3.1-h4ab18f5_1 
  markupsafe         conda-forge/linux-64::markupsafe-2.1.5-py312h98912ed_0 
  ncurses            conda-forge/linux-64::ncurses-6.5-h59595ed_0 
  openssl            conda-forge/linux-64::openssl-3.3.1-h4ab18f5_0 
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  python             conda-forge/linux-64::python-3.12.4-h194c7f8_0_cpython 
  python_abi         conda-forge/linux-64::python_abi-3.12-4_cp312 
  pyyaml             conda-forge/linux-64::pyyaml-6.0.1-py312h98912ed_1 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
  setuptools         conda-forge/noarch::setuptools-70.0.0-pyhd8ed1ab_0 
  sortmerna          bioconda/linux-64::sortmerna-4.3.7-hdbdd923_1 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0 
  urllib3            conda-forge/noarch::urllib3-2.2.2-pyhd8ed1ab_0 
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2 


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

```
(sortmerna_env) odin@odin-PowerEdge-T620:~$ which sortmerna
/home/odin/anaconda3/envs/sortmerna_env/bin/sortmerna
```

But when trying to verify the installation, I have constantly the following error:
```
(sortmerna_env) odin@odin-PowerEdge-T620:~$ sortmerna --version
Illegal instruction (core dumped)
```

I can't figure out what is the issue....

Thank you for your feedback.

**Desktop (please complete the following information):**
 - System version: Ubuntu 22.04.4 LTS

**Comment by biocodz** [comment]
You have installed 4.3.7 version from bioconda channel, which is non-valid and not supposed to be there.
```
mamba search sortmerna
# Name                       Version           Build  Channel
...
sortmerna                      4.3.6      h9ee0642_0  bioconda
sortmerna                      4.3.7      hdbdd923_0  bioconda   <- ?
sortmerna                      4.3.7      hdbdd923_1  bioconda   <- ?
```
Not sure how 4.3.7 got there and with two builds. We have a PR for 4.3.7 on conda-forge since a few months already, which is still not merged.
Please, discard 4.3.7 on bioconda. Either use 4.3.6, or use [pre-built 4.3.7 binaries](https://github.com/sortmerna/sortmerna/releases/tag/v4.3.7).
Sorry for this mess-up

**Comment by rpeguil** [comment]
Thanks. It is now working with version 4.3.6

**Comment by biocodz** [comment]
Created [bioconda-recipes PR 48607](https://github.com/bioconda/bioconda-recipes/pull/48607) to remove sortmerna recipe due relocation to conda-forge

**Comment by luigallucci** [comment]
Hi @biocodz, 

just a note on that. I was trying to install it on a new conda environment using -c conda-forge, having strict channel priority and so on. Unluckily, the installation is still searching it on BioConda with reference to the 4.3.7 which is producing always the same error. I tried to remove bioconda to use just conda-forge, but then is not possible to found sortmerna.

**Comment by biocodz** [comment]
Unfortunately the conda-forge [PR 25438](https://github.com/conda-forge/staged-recipes/pull/25438) is still not merged. The build is broken after some modifications to the conda-build pipeline, and the [issue 5391](https://github.com/conda/conda-build/issues/5391) I filed a month ago still didn't get any response

**Comment by biocodz** [comment]
Until 4.3.7 is available on conda-forge, the installation can be performed using local conda package [sortmerna-4.3.7-conda-linux-64.tar.bz2](https://github.com/sortmerna/sortmerna/releases/download/v4.3.7/sortmerna-4.3.7-conda-linux-64.tar.bz2). Just follow the instructions on the main github page (readme)

**Comment by gq1** [comment]
Hi there.

Does the 4.3.7 version get fixed in BionConda? I use the BioContainer and it seems fine.

```
$ docker run quay.io/biocontainers/sortmerna:4.3.7--hdbdd923_1 sortmerna --version
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --version
[process:1483] Processing option: version with value:

SortMeRNA version 4.3.7
Build Date: Jun 12 2024
sortmerna_build_git_sha:@0@
sortmerna_build_git_date:@2024/06/12 09:30:04@
```

If not, do you have any pre-built container?

Thanks.

**Comment by biocodz** [comment]
Hi,
I was not aware of the sortmerna image on the biocontainers that you reference. It is managed by a third party. If it works fine then it's a good news.
I have attached a docker image [sortmerna-4.3.7-img.tar.gz](https://github.com/sortmerna/sortmerna/releases/download/v4.3.7/sortmerna-4.3.7-img.tar.gz) to the 4.3.7 release in case you need it

**Comment by gq1** [comment]
> I was not aware of the sortmerna image on the biocontainers that you reference. It is managed by a third party. If it works fine then it's a good news.

It comes from BionConda automatically. If you think 4.3.7 has a problem in BionConda then it should have the same problem in BioContainter.

If the image you built works, maybe you can push to some registry, like Docker Hub, or GitHub with your source coe? Thanks.
