### ISSUE TITLE
SortMeRNA Reports Over 90% of Reads as rRNA, and STAR Alignment Still Shows a High Number of rRNA Genes

### ISSUE THREAD

**Issue by Ivy-ops** [sortmerna/sortmerna#428]
Hi developer, 
I am using SortMeRNA to remove rRNA from my metatranscriptome data, and while I expected most rRNA reads to be depleted. The cleaned reads contain 25,721,937 R1 and 25,721,937 R2 reads. The sortmerna output reported that over 94% of the reads are rRNA, while approximately 5% are non-rRNA.
Here is the code I used:
`sortmerna --ref ~/database/rfam-5.8s-database-id98.fasta --ref ~/database/rfam-5s-database-id98.fasta --ref ~/database/silva-arc-16s-id95.fasta --ref ~/database/silva-arc-23s-id98.fasta --ref ~/database/silva-bac-16s-id90.fasta --ref ~/database/silva-bac-23s-id98.fasta --ref ~/database/silva-euk-18s-id95.fasta --ref ~/database/silva-euk-28s-id98.fasta --reads ~/qc_out/S10_R1.fastq.gz --reads ~/qc_out/S10_R2.fastq.gz --workdir ~/sortme_out3/sortmerna_S10 --other ~/sortme_out3/S10_no_rRNA --aligned ~/sortme_out3/S10_rRNA --fastx -e 1000 --num_alignments 1 --threads 8 --paired_in --out2 -blast`

After sortmerna, I used STAR for alignment, I ended up with 12,437 genes mapped, totaling 336,774 counts. Among these, 85,661 counts are from the mt-Rnr1 gene and 99,797 counts are from the mt-Rnr2 gene, which together account for 55% of the mapped genes.

I am wondering if there is anything I did wrong in the SortMeRNA run. I have attached the log file for your reference. Your suggestions would be greatly appreciated!

Attached is my log file. 
[S10_sortmerna.log](https://github.com/user-attachments/files/16843311/S10_sortmerna.log)

**Comment by ekopylova** [comment]
Hello,

Could you provide the first 10 reads classified as rRNA by SortMeRNA (should be in the --aligned file)?

What input did you use for the STAR alignment, the original fastq.gz reads or some output from SortMeRNA?

Thanks!
Jenya

**Comment by Ivy-ops** [comment]
Hi @ekopylova ,

Thank you for the quick response.

Yes, 25,721,937 R1 and 25,721,937 R2 reads have undergone rRNA depletion using SortMeRNA. I've attached the first 10 forward and reverse reads for your reference. 
[S10_rRNA_fwd.txt](https://github.com/user-attachments/files/16852341/S10_rRNA_fwd.txt)
[S10_rRNA_rev.txt](https://github.com/user-attachments/files/16852342/S10_rRNA_rev.txt)

My sequences are a mix of mouse and microbiome sources, so I performed the following steps:

I aligned SortMeRNA's output (S10_no_rRNA_fwd.fq.gz and S10_no_rRNA_rev.fq.gz) to the mouse genome (GCF_000001635.27_GRCm39_genomic) using Bowtie2 and Samtools to extract the mouse sequences.
I then aligned the extracted sequences to the mouse genome again using STAR.
Finally, I used the STAR-aligned file as input for HTSeq-count to generate the gene count table.
Here is the detailed code I used:

```
bowtie2 -p 8 -x $GENOME_INDEX \
  -1 S10_no_rRNA_fwd.fq.gz \
  -2 S10_no_rRNA_rev.fq.gz \
  --very-sensitive-local | \
samtools view -bS - > S10_mapped_and_unmapped.bam

samtools view -b -F 4 S10_mapped_and_unmapped.bam | \
samtools sort -n -m 5G -@ 2 - | \
samtools fastq -@ 8 -1 mice_S10_R1.fastq.gz -2 mice_S10_R2.fastq.gz -0 /dev/null -s /dev/null -n

STAR --runThreadN 10 \
     --genomeDir $STAR_GENOME_DIR \
     --readFilesIn mice_S10_R1.fastq.gz mice_S10_R2.fastq.gz \
     --readFilesCommand zcat \
     --outFileNamePrefix ${star_dir}/S10_ \
     --outSAMtype BAM SortedByCoordinate

aligned_bam="${star_dir}/mice_S10_Aligned.sortedByCoord.out.bam"
htseq-count -f bam -r pos -s no -t exon -i gene_id \
    ${aligned_bam} GCF_000001635.27_GRCm39_genomic.gtf > ${htseq_dir}/mice_S10_counts.txt
```

I would like to hear your suggestions. Thank you!

**Comment by biocodz** [comment]
@Ivy-ops What version of sortmerna do you use? Can you also provide the [execution-trace](https://github.com/sortmerna/sortmerna?tab=readme-ov-file#execution-trace)?

**Comment by Ivy-ops** [comment]
Hi @biocodz , 

Please see the version: 
```
[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --version
[process:1483] Processing option: version with value: 

SortMeRNA version 4.3.6
Build Date: Aug 16 2022
sortmerna_build_git_sha:@db8c1983765f61986b46ee686734749eda235dcc@
sortmerna_build_git_date:@2022/08/16 11:42:59@
```
Please also review the trace. I hope everything is correct, as I submit jobs using samtools, bowtie, STAR, etc., and have omitted the SortMeRNA part.
[output.txt](https://github.com/user-attachments/files/16875634/output.txt)
Thanks so much. Your suggestions are highly appreciated.

**Comment by Ivy-ops** [comment]
@biocodz I am following up about the issue, do you have any suggestions? Thank you!!

**Comment by Ivy-ops** [comment]
@ekopylova Yes, it is pretty helpful! It seems that my datasets really contains a lot of rRNAs. Thank you!!
